######################################################################
##
## Filename: TESTRAM_tb.udo
## Created on: 金 12月 04 14時10分26秒 JST 2015
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
